name: Deploy to Sonatype

on: workflow_dispatch

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml
  deploy:
    needs: [test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Gradle publish
        run: |
          ./gradlew \
            -PGITHUB_PUBLISH_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -PsigningInMemoryKey="${{ secrets.SIGNING_KEY }}" \
            -PsigningInMemoryKeyId="${{ secrets.SIGNING_KEY_ID }}" \
            -PsigningInMemoryKeyPassword="${{ secrets.SIGNING_PASSWORD }}" \
            -PcentralPortal.username="${{secrets.SONATYPE_USERNAME}}" \
            -PcentralPortal.password="${{secrets.SONATYPE_PASSWORD}}" \
            -Ppowersync.binaries.allPlatforms="true" \
            publishAllPublicationsToSonatypeRepository
        shell: bash
