name: All Publish
on:
  workflow_dispatch:
#  push:
#    branches:
#      - "main"

jobs:
  import-gpg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.SIGNING_KEY }}
          passphrase: ${{ secrets.SIGNING_PASSWORD }}
      - name: List keys
        run: gpg -K
  call-kmmbridge-publish:
    needs: import-gpg
    permissions:
      contents: write
      packages: write
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildautoversion.yml@v1.1
    with:
      jvmVersion: 17
      versionBaseProperty: LIBRARY_VERSION
      publishTask: kmmBridgePublish publishKotlinMultiplatformPublicationToGitHubPackagesRepository publishAndroidDebugPublicationToGitHubPackagesRepository publishAndroidReleasePublicationToGitHubPackagesRepository
#    secrets:
#      gradle_params: |
#        -Psigning.gnupg.keyName=${{ secrets.SIGNING_KEY_ID }}
#        -Psigning.gnupg.passphrase=${{ secrets.SIGNING_PASSWORD }}
#      PODSPEC_SSH_KEY: ${{ secrets.PODSPEC_SSH_KEY }}
